ARG BASE_CONTAINER=continuumio/miniconda3
FROM $BASE_CONTAINER

LABEL maintainer="Edgar Felizmenio <edgarfelizmenio@gmail.com>"

USER root

WORKDIR /workspace

# install required packages
RUN apt-get update && apt-get -y upgrade
RUN apt-get install -y libopenblas-dev

# install Jupyterlab
RUN conda install -c conda-forge jupyterlab
RUN conda install -c conda-forge nb_conda_kernels

# install Pytorch
RUN conda install -c conda-forge pytorch

# install R
RUN conda install -c conda-forge r-recommended
RUN conda install -c conda-forge r-irkernel
RUN conda install -c conda-forge r-irdisplay
RUN conda install -c conda-forge r-repr
RUN conda install -c conda-forge r-ggplot2
RUN conda install -c conda-forge r-devtools
RUN conda install -c conda-forge r-ape
RUN conda install -c conda-forge r-hdf5r

# install Seurat
RUN conda install -c conda-forge r-seurat
RUN conda install -c conda-forge r-seuratobject
# RUN conda install -c conda-forge r-seuratdisk
RUN conda install -c bioconda bioconductor-biomart

# Spatial Integration GSI (Rian)
RUN conda install python=3.10
RUN conda install -c bioconda bioconductor-rhdf5
RUN conda install -c bioconda bioconductor-spatiallibd

EXPOSE 8888

ENTRYPOINT ["jupyter", "lab", "--ip=0.0.0.0", "--port=8888", "--allow-root", "--no-browser"]

