ARG BASE_CONTAINER=pytorch/pytorch:latest
FROM $BASE_CONTAINER

LABEL maintainer="Edgar Felizmenio <edgarfelizmenio@gmail.com>"

USER root

WORKDIR /workspace

# install other dependencies

# PyTorch Tutorials
RUN pip install matplotlib
RUN pip install pandas

# GraphST
RUN pip install scanpy
RUN pip install scikit-learn
RUN pip install scikit-misc
RUN pip install POT


# install jupyter lab
RUN pip install jupyterlab

EXPOSE 8888

ENTRYPOINT ["jupyter", "lab", "--ip=0.0.0.0", "--port=8888", "--allow-root", "--no-browser"]

