ARG BASE_CONTAINER=pytorch/pytorch:latest
FROM $BASE_CONTAINER

LABEL maintainer="Edgar Felizmenio <edgarfelizmenio@gmail.com>"

USER root

WORKDIR /workspace

# install other dependencies
RUN pip install matplotlib

# install jupyter lab
RUN pip install jupyterlab

EXPOSE 8888

ENTRYPOINT ["jupyter", "lab", "--ip=0.0.0.0", "--port=8888", "--allow-root", "--no-browser"]

