ARG BASE_CONTAINER=continuumio/miniconda3
FROM $BASE_CONTAINER

LABEL maintainer="Edgar Felizmenio <edgarfelizmenio@gmail.com>"

USER root

WORKDIR /workspace

# install required packages
RUN apt-get update && apt-get -y upgrade
RUN apt-get install -y libopenblas-dev

# install Jupyterlab
RUN conda install -c conda-forge jupyterlab
RUN conda install -c conda-forge nb_conda_kernels


EXPOSE 8888

ENTRYPOINT ["jupyter", "lab", "--ip=0.0.0.0", "--port=8888", "--allow-root", "--no-browser"]

